apiVersion: v1
kind: Service
metadata:
  name: backend-yzts
  labels:
    app: backend-yzts
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: backend-yzts
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-yzts
  labels:
    app: backend-yzts
spec:
  selector:
    matchLabels:
      app: backend-yzts
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: backend-yzts
    spec:
      containers:
      - image: gcr.io/google-project-id/backend-yzts:0.1.1
        name: backend-yzts
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 2
        ports:
        - containerPort: 3000
          name: backend-yzts